# Site settings
title: GTFS.org
email: gtfs-wg@rmi.org
description: > # Resources for the General Transit Feed Specification
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gtfs.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
  reference:
    output: true
  best-practices:
    output: true

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
